### ISSUE TITLE
Scan distance not increasing for me

### ISSUE THREAD

**Issue by HoodedDeath** [Test-Account666/LethalCompany-ScanShipEverywhere#3]
Long story short, the mod manages to add a node for the light switch (haven't tested drop ship yet though), but fails to increase the scan distance for any nodes. Tested one Dine for the Main Entrance scan, got nothing. Created a new save file and tested on the light switch, and found that the scan distance was not increasing.

There's a chance that this is down to my system, as I'm running LC on Linux through Proton-GE, but I've never seen a mod-specific bug show up under Proton.

Perhaps just an issue that's cropped up with v55? Attaching a BepInEx log with all log levels enabled in case it's helpful, but I didn't see anything noteworthy in it myself.

[LogOutput.log](https://github.com/user-attachments/files/16242687/LogOutput.log)

**Comment by Test-Account666** [comment]
Hey!

I'm also running LC on Linux through Proton-GE.

I just pushed version 2.0.0, which should fix your issues :)

**Comment by HoodedDeath** [comment]
Looks like this update got the scan nodes mostly functional again. Still have a few issues, sadly.
1. The default 'Scan Distance Hard Limit' of 800 seems to be too low to see the main entrance from Experimentation's fence line. Setting it to the same value as the max distance settings fixes that though
2. The ship and entrance nodes are very inconsistent with how long they remain visible. In my quick testing tonight, they stayed on screen at most about 2 seconds, at worst not even half a second. Nodes also seem to decide individually how long they'll be visible, so the ship and entrance were each disappearing at different times each time.
3. Nodes inside the ship seem to completely ignore the distance increase

1 isn't a big deal, just a config tweak that makes sense to default low in order to avoid causing lag, but could debatably do with an increase to accommodate the larger maps like March.

Assuming 2 is a bug, what options would be available for me to provide more info to help track the issue down? I'd love to help resolve this and switch to using this instead of ShipScanRange, even if my main motivation is the light switch node.

I'm assuming 3 is intentional to avoid having a bunch of spam nodes show up when trying to find the ship, but personally I'd prefer to have those distances increased, even if it is just to find the light switch when someone hides it. I don't know if it's possible or feasible to make the inside-the-ship nodes only show up if the player is in the ship, so perhaps instead just increasing the max distance for them to roughly the length of the ship?

**Comment by Test-Account666** [comment]
> Looks like this update got the scan nodes mostly functional again. Still have a few issues, sadly.
>
>     1. The default 'Scan Distance Hard Limit' of 800 seems to be too low to see the main entrance from Experimentation's fence line. Setting it to the same value as the max distance settings fixes that though
> 
>     2. The ship and entrance nodes are very inconsistent with how long they remain visible. In my quick testing tonight, they stayed on screen at most about 2 seconds, at worst not even half a second. Nodes also seem to decide individually how long they'll be visible, so the ship and entrance were each disappearing at different times each time.
> 
>     3. Nodes inside the ship seem to completely ignore the distance increase
> 
> 
> 1 isn't a big deal, just a config tweak that makes sense to default low in order to avoid causing lag, but could debatably do with an increase to accommodate the larger maps like March.
> 
> Assuming 2 is a bug, what options would be available for me to provide more info to help track the issue down? I'd love to help resolve this and switch to using this instead of ShipScanRange, even if my main motivation is the light switch node.
> 
> I'm assuming 3 is intentional to avoid having a bunch of spam nodes show up when trying to find the ship, but personally I'd prefer to have those distances increased, even if it is just to find the light switch when someone hides it. I don't know if it's possible or feasible to make the inside-the-ship nodes only show up if the player is in the ship, so perhaps instead just increasing the max distance for them to roughly the length of the ship?

> 1 isn't a big deal, just a config tweak that makes sense to default low in order to avoid causing lag, but could debatably do with an increase to accommodate the larger maps like March.

I'll increase the default next Update :)

> Assuming 2 is a bug, what options would be available for me to provide more info to help track the issue down? I'd love to help resolve this and switch to using this instead of ShipScanRange, even if my main motivation is the light switch node.

First of all... Are you moving? And are you using other Scan Mods?

> I'm assuming 3 is intentional to avoid having a bunch of spam nodes show up when trying to find the ship, but personally I'd prefer to have those distances increased, even if it is just to find the light switch when someone hides it. I don't know if it's possible or feasible to make the inside-the-ship nodes only show up if the player is in the ship, so perhaps instead just increasing the max distance for them to roughly the length of the ship?

The scan distance of ship stuff is already quite big though?

**Comment by HoodedDeath** [comment]
> First of all... Are you moving? And are you using other Scan Mods?

After first seeing that behavior, I switched to a modpack to only has bep and this mod installed, and standing in different spots to scan. The only movement that might've been happening is my camera

> The scan distance of ship stuff is already quite big though?

I don't know how big they're supposed to be, but starting a new save for default ship layout and standing with my back against the landing lever, the scanner can't pick up the light switch or charging coil

**Comment by Test-Account666** [comment]
> After first seeing that behavior, I switched to a modpack to only has bep and this mod installed, and standing in different spots to scan. The only movement that might've been happening is my camera

I cannot reproduce this :/


The vanilla scan has a width attached to it, so you might be better off using one of the compatible scan mods.
I'd recommend GoodItemScan as it works best with this mod in my experience.

**Comment by Test-Account666** [comment]
> I don't know how big they're supposed to be, but starting a new save for default ship layout and standing with my back against the landing lever, the scanner can't pick up the light switch or charging coil

Well, they are supposed to be scannable in a radius of 6 units.

Which should be enough to find a hidden light switch quickly
